### ISSUE TITLE
How to use? (Beginner)

### ISSUE THREAD

**Issue by HijiKili** [mhvuze/ReFrontier#5]
I'm so sorry but I'm new in using source code. Been looking for a whole day how to use Github code but I understand nothing. Did try using Visual Code but also have zero experience and broke it, now my SDK is unrepairable and cannot be detected even after installing all version to 4.0 to 7.0 (+all type of C++/C# extension).

I just wants to extract the monster.pac files for 3D
any help?

**Comment by DeftAlec** [comment]
Hey, I'm not the author but I've been in your shoes before so I think I can help... For simplicity's sake, delete anything associated with the refrontier files you have on your computer, then redownload the zip. Extract it anywhere, just make sure the contents are all in one folder. Find the "ReFrontier.sln" file. Either open it with Microsoft Visual Studio, drag it onto Microsoft Visual Studio, or, if you've opened a sln file with it before, just double click the sln file. Once there, look near the top of the screen, there should be a green arrow close to the center with the word "Start" next to it. Click that, and let it do it's thing. Once that's done, you can close Microsoft Visual Studio, then go back to the ReFrontier folder where you initially found the sln file. Then go into the new "ReFrontier" folder. Then go into the "bin" folder, then "Debug" (should be the only one), then there should be a "ReFrontier.exe" exacutable.
[wherever you downloaded it]\ReFrontier-master\ReFrontier\bin\Debug

At this point, grab whatever .pac files you want to unpack, and simply drag it onto the ReFrontier.exe
Pretty sure it only works if you do one at a time, but I could be remembering wrong..
Good luck, have fun! Hope you find what you're looking for :)

**Comment by HijiKili** [comment]
I see why I cant use the code

_Once there, look near the top of the screen, there should be a green arrow close to the center with the word "Start" next to it. Click that, and let it do it's thing._

I cant find any green button, something might not right. Then I realized the VS I use was "Code" not "Community". Download the correct one and fiola! I able to open the ReFrontier.exe in console cmd

drag and drop the into the Frontier.exe and flawless!
I owe you a coffee man!
